### ISSUE TITLE
spectra displayer - you misunderstood the legend position in jsGraph

### ISSUE THREAD

**Issue by NPellet** [NPellet/visualizer#300]
```javascript

theLegend.setPosition({
        dx: '0px',
        dy: '0px',
        x: 'max',
        y: 'max'
    },
    posX, // Reference point
    posY // Reference point
);
```

posX and posY refer allow you to set the positioning point of the legend. If you take bottom right, the bottom right corner will be adjusted to the position that is specified in the first parameter. You need to use the first parameter to locate the legend in the x and y direction. The two last one are merely to change the internal reference point.

**Comment by targos** [comment]
almost fixed with 4719a246811e305882383b0915890473b0b6696c
when x is set to 'max', you only see half of the legend

http://direct.lactame.com/visualizer/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/jcampViewer/view.json&dataURL=../testcase/data/jcampViewer/data.json
