### ISSUE TITLE
Slick grid remove focus on refresh

### ISSUE THREAD

**Issue by David-Turbert** [NPellet/visualizer#354]
When I select a line and i refresh, the focus stay on the old line

**Comment by lpatiny** [comment]
What do you mean by refresh ? Change the input variable ?
Seems to me it is the expected behaviour so that if we change a field in the array we don't loose the focus in the table.
There is an action that allows to go to first line if you need to go back to the top of the table.

**Comment by David-Turbert** [comment]
In my case, i have a "Slick Grid" powered by an variable from a "Webservice search" with a input variable who filter the result of it, but when i perform an other search my focus stay on the older row. What i would like, it is an option who leave all focus when data change.

**Comment by lpatiny** [comment]
Indeed it could be an option and remove the "default" behaviour that keeps the current selected line if the number of rows didn't change.

**Comment by stropitek** [comment]
I'm adding an option.
You have now two options for the scroll on new variable behaviour:
- You can choose not to remember to scroll position on new var
- You can choose not to remember to scroll to last active (a cell is active if it is focusable and has been selected) cell
If you uncheck both,  then "scroll to last active cell" has precedence. If you choose to check both options you will have your expected behaviour (no scrolling or focus at all)
