### ISSUE TITLE
Highligth on slick grid

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#438]
Highligth does not work until you open and close the properties menu.

Testcase: http://visualizer.epfl.ch/tiny/jq3H1muwSocesEylkDQt ([Original URL](http://www.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FVgh2HC1FZg%2Ftest%40patiny.com%2FResearch%2FNMR%2FPeakPickingNew%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FTk0OZB692Z%2Ftest%40patiny.com%2FResearch%2FNMR%2FPeakPickingNew%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by stropitek** [comment]
It seems to work well for me...

**Comment by lpatiny** [comment]
The problem here is that the _highlight of cosyPL is changed in another script and the module slick grid is not aware about the change.
One way to solve this kind of problem is to tell a variable that it has changed using
myVar.triggerChange()
However in this specific case it would create an event loop that will rather crash the browser ...
So in this specific case the 2 filters have been joined.
