### ISSUE TITLE
markerIndependent option in jsgraph

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#477]
When moving on the chart the highlight does not always work.

There is also 2 other problems:

Moving the scrollbar of slickgrid with a highlight present may be chaotic
Mouse scroll may also give erratic behaviour

Testcase: http://visualizer.epfl.ch/tiny/a8mOLNiqKM7wcDKha7FB ([Original URL](http://www.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FViIQGMVvIN%2Ftest%40patiny.com%2FResearch%2FBio%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FO6NthE96dB%2Ftest%40patiny.com%2FResearch%2FBio%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by stropitek** [comment]
The problem comes from the jsgraph scatter module. When points are superimposed, the mouseenter and mouseleave events do not trigger correctly. Therefore slick grid thinks some highlights are still active when they are not in reality. For now I've added an option so that slick grid does not scroll to the highlighted element. See 4098d79f40dc3eda76d0fa747f04d93e441d0ece. But the problem should be corrected in jsgraph.

**Comment by stropitek** [comment]
See NPellet/jsgraph#32

**Comment by targos** [comment]
I think this is fixed now

**Comment by stropitek** [comment]
I don't see anything in spectra_displayer that sets jsgraph's ```markersIndependent``` option...
Default is false

**Comment by targos** [comment]
you are right :confused:.
Anyway now the highlight has a problem: https://github.com/NPellet/jsGraph/issues/45
