### ISSUE TITLE
Escape in URL bug

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#480]
In the current view the PNG molecule URL is not formatted correctly for the molecule depictor. The incoming URL's are correct (original JSON)[http://script.epfl.ch/script/renders/jsonreport/index.html?url=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FHD%2FLoad%2Fqvy2bZYkTt%3Ffilename%3Dtest%2540patiny.com%252FResearch%252FNMR%252FJCoupling%252F.results%252FMaster%252F1428942589032.json]

"Should be
http://script.epfl.ch/moleculeDepictor/MoleculeDepictor?moleculeId=deTH%60ABHRYWZf%60%40f%40%40&color=true
And it is
http://script.epfl.ch/moleculeDepictor/MoleculeDepictor?moleculeId=deTH%2560ABHRYWZf%2560%2540f%2540%2540&color=true
You see this %2560" LP

Testcase: http://visualizer.epfl.ch/tiny/fs0II7aSWxp6onAi5le2 ([Original URL](http://www.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FoYOuIc7OJT%2Ftest%40patiny.com%2FResearch%2FNMR%2FJCoupling%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FTgkjBkPmcb%2Ftest%40patiny.com%2FResearch%2FNMR%2FJCoupling%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by andcastillo** [comment]
Perhaps you need the original view, because in the given URL it works.
(view) [http://www.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FoYOuIc7OJT%2Ftest%40patiny.com%2FResearch%2FNMR%2FJCoupling%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FTgkjBkPmcb%2Ftest%40patiny.com%2FResearch%2FNMR%2FJCoupling%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json]

**Comment by targos** [comment]
no worries, the original URL is also provided in the bug report, but thanks
