### ISSUE TITLE
Detect and allow to step out of infinite action loops

### ISSUE THREAD

**Issue by targos** [NPellet/visualizer#502]
Would allow to fix problems like in #501 and #486.

**Comment by andcastillo** [comment]
Thanks by the suggestions about how to go around the problem, but neither vi and edit the module manually nor change to version v2.7.3 is a valid solution  because the module is in visualizer.epfl.ch. I don't know where exactly in the database is the view and how can I edit it, and if I change the version I can't access to the couchDB menu.
