### ISSUE TITLE
CK editor can not be loaded in the last release 2.17.5 ?

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#506]
Check the error log of this view.

What I would like to do in this view:
1. be able to edit the description
2. Share view
3. Based on the shared view link see my edited text

Please could you check if it works ? I have the impression there is a conflict between the input variable if defined and the predefined value of the Rich Text Editor that seems to be saved in the view. 

There is no option to specify if the result of the edition should be saved in the view or in the variable. How it is managed ?

Testcase: http://visualizer.epfl.ch/tiny/hh8WK8qLXhLuNDpf3KKk ([Original URL](http://direct.lactame.com/visualizer/v2.17.5/index.html?viewURL=http://visualizer.epfl.ch/x/bJ7YXU3n9RPQpsPhJpdV/view.json&dataURL=http://visualizer.epfl.ch/x/bJ7YXU3n9RPQpsPhJpdV/data.json))

**Comment by lpatiny** [comment]
In fact seems this issue is related to french language ... I was using my son computer, should but it by default to english ;)

GET http://www.lactame.com/visualizer/v2.17.5/components/ckeditor/lang/fr.js?t=F0RF CKEDITOR.tools.extend.append @ ckeditor.js:69CKEDITOR.tools.extend.appendTo @ ckeditor.js:47q @ ckeditor.js:210CKEDITOR.scriptLoader.load @ ckeditor.js:210CKEDITOR.lang.load @ ckeditor.js:208h @ ckeditor.js:223(anonymous function) @ ckeditor.js:223b @ ckeditor.js:432CKEDITOR.skin.loadPart @ ckeditor.js:434f @ ckeditor.js:223(anonymous function) @ ckeditor.js:223h @ ckeditor.js:10CKEDITOR.event.CKEDITOR.event.fire @ ckeditor.js:11CKEDITOR.editor.CKEDITOR.editor.fire @ ckeditor.js:13CKEDITOR.event.CKEDITOR.event.fireOnce @ ckeditor.js:12CKEDITOR.editor.CKEDITOR.editor.fireOnce @ ckeditor.js:13d @ ckeditor.js:221(anonymous function) @ ckeditor.js:221g.push.callback @ ckeditor.js:211k @ ckeditor.js:209n @ ckeditor.js:209o @ ckeditor.js:209(anonymous function) @ ckeditor.js:210
ckeditor.js:207 Uncaught TypeError: Cannot set property 'dir' of undefinede @ ckeditor.js:207k @ ckeditor.js:209n @ ckeditor.js:209o @ ckeditor.js:209d.$.onerror @ ckeditor.js:210

Failed to load resource: the server responded with a status of 404 (Not Found)
/visualizer/v2.17.5/components/ckeditor/ckeditor.js:208 Uncaught TypeError: Cannot set property 'dir' of undefined
jsoneditor.map:1 GET http://www.lactame.com/visualizer/v2.17.5/components/jsoneditor/jsoneditor.map 404 (Not Found)

**Comment by targos** [comment]
OK I see... The build process keeps only the English language file.
I will force the editor to ignore the user's locale and always use English
