### ISSUE TITLE
3D scatter plot: color specified as RGBA

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#611]
Seems that the color of an object can not be specified as a RGBA

         "rgba(0,0,255,1)"

However RGB works perfectly. Is this normal ?

Testcase: http://visualizer.epfl.ch/tiny/sm9bLnRoWqACa8WSZlwf ([Original URL](http://visualizer.epfl.ch/c/home/index.html))

**Comment by stropitek** [comment]
You can't because the opacity is separate from the color in threejs/webgl. I don't know how we could set the opacity as a varying parameter, since you need to make the image transparent (I have each shape image twice, one opaque for normal point and another transparent for highlights).
For now I will just remove the opacity component from the color if there is one
