### ISSUE TITLE
slickgrid and two webservice is looping

### ISSUE THREAD

**Issue by David-Turbert** [NPellet/visualizer#642]
I can't explain just folow this instructions:
step1: clic "Go"
step2: select a line
step3: clic delete
step4: clic new
step5: fill values
step6: clic save

example:
https://[...].cheminfo.org/couch/virago/home/index.html?viewURL=%2Fcouch%2Fvirago%2F162a07320ce1f413c3487eda42457364%2Fview.json

**Comment by stropitek** [comment]
This behaviour is a normal behaviour of the visualizer. The webservice 2 listens to a a variable (the last element of the array) that will always fire a change event when the list is updated. To circumvent that you have to use actions instead of variables. If you really need a variable as input of the webservice, then you can use action with an intermediate code executor that create an independent variable. See http://visualizer.epfl.ch/tiny/vu0B1UYN57duOddmHMJG
