### ISSUE TITLE
slick grid and variable out from generated data

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#731]
When clicking on a line you get the information about all what is available on the right.

When you click on one of the line on the right there is no variable out generated ?

Testcase: http://visualizer.epfl.ch/tiny/YWyUMlsJmmYQzx4yIbq1 ([Original URL](http://visualizer.epfl.ch/c/home/index.html?v=v2.28.4&viewURL=%2Fc%2F16e029673e68d05b6df709e297c72652%2Fview.json))

**Comment by stropitek** [comment]
You use a filter that transforms an object into an array. Since hover and click use jpaths to set variables it cannot work.
What you are trying to access when clicking a line in the second table is ["filter", r1, r2], where r1 is the row hovered in the first table and r2 is the row clicked in the second table, which is undefined.

**Comment by lpatiny** [comment]
OK I don't use filter anymore in this case I create a new variable with a Code Executor
