### ISSUE TITLE
Upload large files with couchDB button

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#790]
I'm trying to upload 200 files of 1Mb each but the system crash. Only 50 at a time seems reliable.

**Comment by stropitek** [comment]
Are you doing it programatically or do you use the couchdb attachments user interface?

**Comment by stropitek** [comment]
ah ok just saw the title :)

**Comment by stropitek** [comment]
I'm trying to be smart with how I upload attachments, but apparently not enough.
The way it works now is that all "small" attachments are being uploaded inline, whereas big attachments are uploaded one by one. Small is considered < 10MB
So obviously the problem here is that we have a huge inline upload request

If you want this to work I can add some code that makes several inline requests if needed

**Comment by lpatiny** [comment]
I think it should be by batch that is send as soon as you reach 10Mb or something like that
In my case I have 200 attachments of 1Mb so I guess it would still fail no

**Comment by targos** [comment]
should be fixed
