### ISSUE TITLE
qrcode and resolution

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#827]
We would need to be able to define resolution (or density) of the qrcode. The idea would be that I can define a width of 500 and height of 500 but that at the end I have a barcode of 100x100 because we force the scale down in the <img> tag.

Printing QR code yield to a higher resolution that the screen and like that we can do pretty (and readable) small QRcode.

I don't know if there is any support for this in the library

**Comment by stropitek** [comment]
I changed the qrcode library we use in the visualizer and I made a fork of it to support this. You can use the renderer options `pointWidth` and `pointHeight` now

This library can render the qrcode as a table or canvas but not as an image. I made table the default in the typerenderer so that it works with reports. Quiet dom-heavy to have this table though...

Pull request: https://github.com/jeromeetienne/jquery-qrcode/pull/80

**Comment by stropitek** [comment]
Don't think this repo is going change any time soon.

We'll stick to our fork
