### ISSUE TITLE
spectra displayer and annotation does not work

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#835]
![image](https://cloud.githubusercontent.com/assets/1484241/13723681/d98bcf02-e86c-11e5-896f-e00558bab785.png)

**Comment by targos** [comment]
cc @NPellet. Introduced by https://github.com/NPellet/jsGraph/commit/c624ce65926bf724e998442d967eafd00ca18f4d

**Comment by NPellet** [comment]
Can I see the generation json ?

**Comment by NPellet** [comment]
Ok well you can try using { relativeTo: "((position([0-9]+)|(labelPosition([0-9]+)))" }

But the position must already exist beforehand, otherwise relativeTo will have to effect. Using the api:

shape.getPosition( 0 ).relativeTo( shape.getPosition( 1 ) ); would be much safer if you want to use relative positionning

**Comment by targos** [comment]
It was broken even without using `relativeTo`. Anyway 1.13.3-55 fixed it, thanks
