### ISSUE TITLE
Slick grid should receive action in the script

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#886]
It is possible to define action buttons in the preferences of slick grid.

However this action is not received in the slick grid script.

It would be nice if we could do something directly in the slick grid script when clicking on one of those actions row.
In my particular case I need to create an action that allows to duplicate the current row and I don't see how to do it currently.

**Comment by stropitek** [comment]
Slick grid requires each row to have a property that is unique among all elements in the array.  So duplicating needs some additional logic. This logic is handled in the `addRow` action in event. I just modified it so that it handles multiple rows. So now all you have to do is use the duplicate action as an action in of slickgrid and it will work.

**Comment by stropitek** [comment]
Of course for other purposes it would be useful to have those actions in the slick grid script. I could add that as well
