### ISSUE TITLE
jsGraph breaking change in 1.13.3-91

### ISSUE THREAD

**Issue by NPellet** [NPellet/visualizer#902]
Hey there,

Just as a FYI, I commited a breaking change in the way mouse actions are defined.

The option ```pluginAction``` is replaced (but should be backward compatible) by ```mouseActions``` which is an array.
Example:

```
var graph = new Graph( domGraph, { 
			
		plugins: {
			 'zoom': { zoomMode: 'xy', transition: true },
			 'drag': {
		          persistanceX: true,
		          dragY: false
		        },

		},

		mouseActions: [
			{ plugin: 'zoom', shift: true, ctrl: false },
			{ plugin: 'drag', shift: false, ctrl: false },
			{ callback: function( ) { console.log('sd'); }, shift: true, alt: true },
			{ callback: function() { console.log('mousemove') }, shift: true, type: 'mousemove' },
			{ plugin: 'zoom', shift: true, type: 'mousewheel', options: { baseline: 0, direction: 'y' } },
			{ plugin: 'zoom', shift: true, type: 'dblclick', options: { mode: 'gradualXY' } }
		], ...
});
```

Now, the option dblClick and mousewheel are no longer working in their old format as I could not make them backward compatible so easily.
This way, you can use your own methods for your own defined mouse events.

I'd appreciate you'd let me know if you find any bug in your examples.

**Comment by NPellet** [comment]
PS: default ```type``` is mousedown

**Comment by lpatiny** [comment]
Looks interesting thanks. Would it be possible to change the mouseActions after the instance of jsGraph has been created. The idea would be that if you click on an integral button you can draw integral but after you may switch to a pan or zoom button. Or even a peak picking that would require to draw a rectangle of the zone you want to analyse (this could be a problem because it seems it is the zoom module that takes care of drawing the rectangle).
We would like to move towards the ultimate NMR assignment application ...

**Comment by NPellet** [comment]
Theoretically you have access to graph.options.mouseActions, so yes.

2016-06-07 9:31 GMT+02:00 lpatiny <notifications@github.com>:
